### ISSUE TITLE
Using utf-8 as default encoding？

### ISSUE THREAD

**Issue by FledgeXu** [AlwaysRightInstitute/SwiftXmlRpc#2]
For now the default encoding of the Client is `isoLatin1`, but `utf-8` is more useful for multi-language support. So maybe changing default encoding from `isoLatin1` to  `utf-8` is a better idea?
https://github.com/helje5/SwiftXmlRpc/blob/f8ce064c3108efd73e7f3c3651707538e8b364d1/Sources/XmlRpc/XmlRpcClient.swift#L96

**Comment by helje5** [comment]
Back when it was actively used, XML-RPC used to use Latin-1, that's why a lot of actual services (which are usually very old) are configured that way and  clients the same. Including the service I use it with (old home automation system).

I.e. Latin-1 is actually intended for larger platform support. (I think the Java implementations started to use UTF-8 more commonly)

Even though I don't care too much I think I'll stick to Latin-1 as the default. Most actual services still using XML-RPC are most likely to use that. UTF-8 era services usually do SOAP, not XML-RPC.

Summary: It is tricky to say what the better option is. And it is configurable because of that.
